export default [
  {
    id: 0,
    name: 'Lost And Found',
    type: 'ep',
    date: '2008.09.23',
    title: '미아',
  },
  {
    id: 1,
    name: 'Growing UP',
    type: '정규',
    date: '2009.04.23',
    title: 'Boo',
  },
  {
    id: 2,
    name: 'IU...IM',
    type: 'EP',
    date: '2009.11.12',
    title: '마쉬멜로우',
  },
  {
    id: 3,
    name: '첫사랑이죠',
    type: '싱글',
    date: '2010.01.12',
    title: '첫사랑이죠',
  },
  {
    id: 4,
    name: '텔레시네마 프로젝트 Vol.6',
    type: '싱글',
    date: '2010.02.24',
    title: '다섯째 손가락',
  },
  {
    id: 5,
    name: '잔소리',
    type: '싱글',
    date: '2010.06.03',
    title: '잔소리(With 2AM 슬옹)',
  },
  {
    id: 6,
    name: '사랑의 리퀘스트',
    type: '디지털',
    date: '2010.08.02',
    title: '사랑을 믿어요',
  },
  {
    id: 7,
    name: '그대네요',
    type: '싱글',
    date: '2010.09.28',
    title: '그대네요',
  },
  {
    id: 8,
    name: 'Real',
    type: 'ep',
    date: '2010.12.09',
    title: '좋은 날',
  },
  {
    id: 9,
    name: 'Real+',
    type: '싱글',
    date: '2011.02.17',
    title: '나만 몰랐던 이야기',
  },
  {
    id: 10,
    name: '얼음꽃',
    type: '싱글',
    date: '2011.06.21',
    title: '얼음꽃 (Feat. 김세황)',
  },
  {
    id: 11,
    name: 'Modern Times',
    type: '정규',
    date: '2013.10.08',
    title: '분홍신',
  },
  {
    id: 12,
    name: 'Modern Times - Epilogue',
    type: '정규',
    date: '2013.12.20',
    title: '금요일에 만나요 (Feat. 장이정 OF HISTORY)',
  },
  {
    id: 13,
    name: '봄 사랑 벚꽃 말고',
    type: '싱글',
    date: '2014.04.08',
    title: '봄 사랑 벚꽃 말고',
  },
  {
    id: 14,
    name: '꽃갈피',
    type: 'ep',
    date: '2014.05.16',
    title: '나의 옛날이야기',
  },
  {
    id: 15,
    name: '애타는 마음',
    type: '싱글',
    date: '2014.06.30',
    title: '애타는 마음',
  },
  {
    id: 15,
    name: '애타는 마음',
    type: '싱글',
    date: '2014.06.30',
    title: '애타는 마음',
  },
  {
    id: 16,
    name: '마음',
    type: '싱글',
    date: '2015.05.18',
    title: '마음',
  },
  {
    id: 17,
    name: 'CHAT-SHIRE',
    type: 'ep',
    date: '2015.10.23',
    title: '스물셋',
  },
  {
    id: 18,
    name: '결정 (Feat. 아이유)',
    type: '싱글',
    date: '2016.09.22',
    title: '결정 (Feat. 아이유)',
  },
  {
    id: 19,
    name: '밤편지',
    type: '싱글',
    date: '2017.03.24',
    title: '밤편지',
  },
  {
    id: 20,
    name: '사랑이 잘',
    type: '싱글',
    date: '2017.04.07',
    title: '사랑이 잘 (With 오혁)',
  },
  {
    id: 21,
    name: 'Palette',
    type: '정규',
    date: '2017.04.21',
    title: '팔레트 (Feat. G-DRAGON)',
  },
  {
    id: 22,
    name: '꽃갈피 둘',
    type: 'EP',
    date: '2017.09.22',
    title: '잠 못 드는 밤 비는 내리고',
  },
  {
    id: 23,
    name: '삐삐',
    type: '싱글',
    date: '2018.10.10',
    title: '삐삐',
  },
  {
    id: 24,
    name: 'Love poem',
    type: 'ep',
    date: '2019.11.18',
    title: 'Blueming',
  },
  {
    id: 25,
    name: '첫 겨울이니까',
    type: '싱글',
    date: '2019.12.09',
    title: '첫 겨울이니까',
  },
  {
    id: 26,
    name: '에잇',
    type: '싱글',
    date: '2020.05.06',
    title: '에잇(Prod.&Feat. SUGA of BTS)',
  },
  {
    id: 27,
    name: 'I-LAND Part.1 Signal Song',
    type: '싱글',
    date: '2020.06.19',
    title: 'into the I-LAND',
  },
  {
    id: 28,
    name: "IU 5th Album 'LILAC'",
    type: '정규',
    date: '2021.03.25',
    title: '라일락',
  },
  {
    id: 29,
    name: 'strawberry moon',
    type: '싱글',
    date: '2021.10.19',
    title: 'strawberry moon',
  },
  {
    id: 30,
    name: '조각집',
    type: 'ep',
    date: '2021.12.29',
    title: '겨울잠',
  },
];
